#!/usr/bin/env node
// Builds data/finance.sqlite: a deterministic, SYNTHETIC dataset for "Norte Analytics S.L.",
// a fictional company. Same seed → same bytes of data → same hash in every run record.
import { DatabaseSync } from 'node:sqlite';
import { mkdirSync, rmSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FILE = join(ROOT, 'data', 'finance.sqlite');
mkdirSync(dirname(FILE), { recursive: true });
if (existsSync(FILE)) rmSync(FILE);

// Mulberry32: small, deterministic PRNG.
let seed = 20260919;
const rand = () => {
  seed |= 0; seed = (seed + 0x6d2b79f5) | 0;
  let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
  t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};
const round = (v, d = 0) => Math.round(v * 10 ** d) / 10 ** d;

const db = new DatabaseSync(FILE);
db.exec(`
CREATE TABLE _about (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE _dictionary (table_name TEXT, column_name TEXT, unit TEXT, description TEXT);

CREATE TABLE revenue_monthly (
  month TEXT NOT NULL, region TEXT NOT NULL, product TEXT NOT NULL,
  revenue_eur REAL NOT NULL, units INTEGER NOT NULL,
  PRIMARY KEY (month, region, product));

CREATE TABLE pnl_monthly (
  month TEXT NOT NULL, line TEXT NOT NULL, line_order INTEGER NOT NULL, amount_eur REAL NOT NULL,
  PRIMARY KEY (month, line));

CREATE TABLE ebitda_bridge (
  step_order INTEGER PRIMARY KEY, step TEXT NOT NULL, amount_eur REAL NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('level','movement')));

CREATE TABLE headcount (
  month TEXT NOT NULL, department TEXT NOT NULL, fte REAL NOT NULL,
  PRIMARY KEY (month, department));

CREATE TABLE customers (
  segment TEXT PRIMARY KEY, accounts INTEGER NOT NULL, arr_eur REAL NOT NULL,
  nps INTEGER NOT NULL, churn_rate_pct REAL NOT NULL);
`);

const about = db.prepare('INSERT INTO _about VALUES (?, ?)');
about.run('company', 'Norte Analytics S.L. (fictional)');
about.run('nature', 'SYNTHETIC sample data generated by scripts/build-db.mjs with a fixed seed. Not real figures.');
about.run('currency', 'EUR');
about.run('period', '2025-01 to 2026-06, monthly');
about.run('seed', String(20260919));

const dict = db.prepare('INSERT INTO _dictionary VALUES (?, ?, ?, ?)');
[
  ['revenue_monthly', 'month', 'YYYY-MM', 'Calendar month'],
  ['revenue_monthly', 'region', null, 'Iberia, France, DACH, Nordics, UK'],
  ['revenue_monthly', 'product', null, 'Reports, Dashboards, Advisory'],
  ['revenue_monthly', 'revenue_eur', 'EUR', 'Recognised revenue in the month'],
  ['revenue_monthly', 'units', 'count', 'Deliverables invoiced in the month'],
  ['pnl_monthly', 'line', null, 'P&L line; costs are negative amounts'],
  ['pnl_monthly', 'line_order', null, 'Presentation order of the P&L line'],
  ['pnl_monthly', 'amount_eur', 'EUR', 'Signed amount: revenue positive, costs negative'],
  ['ebitda_bridge', 'kind', null, "'level' rows are opening/closing EBITDA; 'movement' rows are signed drivers"],
  ['ebitda_bridge', 'amount_eur', 'EUR', 'Level or signed movement. Opening + movements = closing, exactly.'],
  ['headcount', 'fte', 'FTE', 'Full-time equivalents at month end'],
  ['customers', 'arr_eur', 'EUR', 'Annual recurring revenue by segment'],
  ['customers', 'churn_rate_pct', '%', 'Trailing-12-month logo churn'],
].forEach(r => dict.run(...r));

const months = [];
for (let y = 2025; y <= 2026; y++) for (let m = 1; m <= 12; m++) {
  if (y === 2026 && m > 6) break;
  months.push(`${y}-${String(m).padStart(2, '0')}`);
}

const regions = { Iberia: 1.0, France: 0.72, DACH: 0.64, Nordics: 0.31, UK: 0.48 };
const products = { Reports: [42000, 1800], Dashboards: [31000, 2600], Advisory: [18000, 9500] };
const rev = db.prepare('INSERT INTO revenue_monthly VALUES (?, ?, ?, ?, ?)');
months.forEach((month, i) => {
  const season = 1 + 0.08 * Math.sin((i / 12) * 2 * Math.PI - 1.2) - (month.endsWith('-08') ? 0.18 : 0);
  const growth = 1 + i * 0.017;
  for (const [region, w] of Object.entries(regions)) {
    for (const [product, [base, price]] of Object.entries(products)) {
      const nordicsLaunch = region === 'Nordics' && product === 'Dashboards' && i >= 12 ? 1.6 : 1;
      const revenue = round(base * w * season * growth * nordicsLaunch * (0.93 + rand() * 0.14));
      rev.run(month, region, product, revenue, Math.max(1, Math.round(revenue / price)));
    }
  }
});

const pnl = db.prepare('INSERT INTO pnl_monthly VALUES (?, ?, ?, ?)');
const revTotal = db.prepare('SELECT SUM(revenue_eur) AS r FROM revenue_monthly WHERE month = ?');
months.forEach((month, i) => {
  const r = round(revTotal.get(month).r);
  const cogs = -round(r * (0.31 + rand() * 0.03));
  const people = -round(118000 + i * 2600 + rand() * 4000);
  const marketing = -round(r * 0.07 + (month === '2026-03' ? 38000 : 0));
  const cloud = -round(14500 + i * 420 + rand() * 900);
  const ga = -round(21000 + rand() * 2500);
  const ebitda = round(r + cogs + people + marketing + cloud + ga);
  [['Revenue', 1, r], ['Cost of sales', 2, cogs], ['People', 3, people], ['Marketing', 4, marketing],
    ['Cloud & tooling', 5, cloud], ['G&A', 6, ga], ['EBITDA', 7, ebitda]]
    .forEach(([line, order, amount]) => pnl.run(month, line, order, amount));
});

// EBITDA bridge FY2025 H1 → FY2026 H1, reconciled exactly from pnl_monthly.
const half = (y, line) => db.prepare(
  `SELECT SUM(amount_eur) AS v FROM pnl_monthly WHERE line = ? AND month BETWEEN '${y}-01' AND '${y}-06'`).get(line).v;
const lines = ['Revenue', 'Cost of sales', 'People', 'Marketing', 'Cloud & tooling', 'G&A'];
const bridge = db.prepare('INSERT INTO ebitda_bridge VALUES (?, ?, ?, ?)');
const open = round(half(2025, 'EBITDA'), 2);
bridge.run(1, 'EBITDA H1 2025', open, 'level');
let acc = open;
lines.forEach((line, k) => {
  const delta = round(half(2026, line) - half(2025, line), 2);
  acc = round(acc + delta, 2);
  bridge.run(k + 2, line === 'Revenue' ? 'Revenue growth' : `${line} change`, delta, 'movement');
});
bridge.run(lines.length + 2, 'EBITDA H1 2026', acc, 'level');

const hc = db.prepare('INSERT INTO headcount VALUES (?, ?, ?)');
const depts = { Engineering: 21, Delivery: 17, Sales: 9, Marketing: 4, 'G&A': 6 };
months.forEach((month, i) => {
  for (const [d, base] of Object.entries(depts)) {
    const g = d === 'Engineering' ? 0.45 : d === 'Delivery' ? 0.3 : 0.12;
    hc.run(month, d, round(base + i * g + (rand() < 0.2 ? 0.5 : 0), 1));
  }
});

const cust = db.prepare('INSERT INTO customers VALUES (?, ?, ?, ?, ?)');
[['Enterprise', 38, 2140000, 46, 4.1], ['Mid-market', 142, 1880000, 38, 9.7],
  ['SMB', 511, 910000, 29, 21.4], ['Public sector', 17, 620000, 51, 2.9]]
  .forEach(r => cust.run(...r));

const check = db.prepare(`SELECT
  (SELECT amount_eur FROM ebitda_bridge WHERE step_order = 1) +
  (SELECT SUM(amount_eur) FROM ebitda_bridge WHERE kind = 'movement') -
  (SELECT amount_eur FROM ebitda_bridge WHERE step_order = (SELECT MAX(step_order) FROM ebitda_bridge)) AS residual`).get();
if (Math.abs(check.residual) > 0.005) throw new Error(`Bridge does not reconcile: residual ${check.residual}`);
db.close();
console.log(`[ok] ${FILE} · ${months.length} months · bridge residual ${check.residual.toFixed(2)}`);
